import{useEffect,useMemo,useState}from'react'
const VERSION='0.6.0',BINGO=30,RESERVE=42
type P={id:string;name:string;x:number;y:number;heading:number;speed:number;alt:number;fuel:number;airborne:boolean;friendly:boolean;trail:{x:number;y:number}[]}
type Base={id:string;name:string;x:number;y:number;aircraft:number}
const bases:Base[]=[{id:'L',name:'LOSSIEMOUTH',x:32,y:20,aircraft:2},{id:'C',name:'CONINGSBY',x:68,y:72,aircraft:2}]
const initialT:P[]=[{id:'T421',name:'TRACK 421',x:82,y:30,heading:245,speed:430,alt:280,fuel:100,airborne:true,friendly:false,trail:[]},{id:'T315',name:'TRACK 315',x:24,y:67,heading:42,speed:390,alt:240,fuel:100,airborne:true,friendly:false,trail:[]}]
const initialF:P[]=[{id:'F21',name:'TYPHOON 21',x:68,y:72,heading:315,speed:450,alt:250,fuel:88,airborne:false,friendly:true,trail:[]},{id:'F22',name:'TYPHOON 22',x:32,y:20,heading:135,speed:450,alt:250,fuel:78,airborne:false,friendly:true,trail:[]}]
const tanker={x:58,y:34,heading:90,speed:410}
const clamp=(n:number,a=4,b=96)=>Math.max(a,Math.min(b,n))
const move=(p:P):P=>{const r=p.heading*Math.PI/180,s=.00115;return{...p,x:clamp(p.x+Math.sin(r)*p.speed*s),y:clamp(p.y-Math.cos(r)*p.speed*s),fuel:p.airborne&&p.friendly?Math.max(0,p.fuel-.045):p.fuel,trail:[...p.trail,{x:p.x,y:p.y}].slice(-22)}}
const d=(a:{x:number;y:number},b:{x:number;y:number})=>Math.hypot(a.x-b.x,a.y-b.y)
const brg=(a:P,b:P)=>Math.round((Math.atan2(b.x-a.x,-(b.y-a.y))*180/Math.PI+360)%360)
const ang=(a:number,b:number)=>Math.abs(((a-b+540)%360)-180)
function solution(f:P,t:P){const dx=t.x-f.x,dy=t.y-f.y,r=t.heading*Math.PI/180,tvx=Math.sin(r)*t.speed,tvy=-Math.cos(r)*t.speed,a=tvx*tvx+tvy*tvy-f.speed*f.speed,b=2*(dx*tvx+dy*tvy),c=dx*dx+dy*dy;let s=0,disc=b*b-4*a*c;if(Math.abs(a)>.0001&&disc>=0){const rs=[(-b-Math.sqrt(disc))/(2*a),(-b+Math.sqrt(disc))/(2*a)].filter(x=>x>0);if(rs.length)s=Math.min(...rs)}if(!s)s=Math.max(1,d(f,t)*.9);const x=clamp(t.x+Math.sin(r)*t.speed*s*.00115),y=clamp(t.y-Math.cos(r)*t.speed*s*.00115);return{sec:s,x,y,heading:Math.round((Math.atan2(x-f.x,-(y-f.y))*180/Math.PI+360)%360)}}
function Contact({p,sel,onClick}:{p:P;sel:boolean;onClick:()=>void}){return <button className={`contact ${p.friendly?'friendly':'hostile'} ${sel?'selected':''}`} style={{left:`${p.x}%`,top:`${p.y}%`}} onClick={onClick}><span className="trail">{p.trail.map((q,i)=><i key={i} style={{left:`${(q.x-p.x)*4}px`,top:`${(q.y-p.y)*4}px`,opacity:(i+1)/p.trail.length*.35}}/>)}</span><span className="bug" style={{transform:`translate(-50%,-100%) rotate(${p.heading}deg)`}}/><span className="symbol">{p.friendly?'▲':'◆'}</span><small>{p.name}</small></button>}
export default function App(){
 const[t,setT]=useState(initialT),[f,setF]=useState(initialF),[selT,setSelT]=useState('T421'),[selF,setSelF]=useState('F21'),[vector,setVector]=useState(285),[base,setBase]=useState('C'),[score,setScore]=useState(0),[running,setRunning]=useState(true),[assist,setAssist]=useState(true),[msg,setMsg]=useState('CONTACT! Assess the fuel state and select the most suitable response.'),[events,setEvents]=useState<string[]>([])
 const target=t.find(x=>x.id===selT)!,fighter=f.find(x=>x.id===selF)!,b=bases.find(x=>x.id===base)!,rng=d(fighter,target)*14,bearing=brg(fighter,target),sol=useMemo(()=>solution(fighter,target),[fighter,target])
 const baseRange=d(fighter,b)*14, tankerRange=d(fighter,tanker)*14, fuelToBase=baseRange/Math.max(1,fighter.speed)*60/10, fuelAtIntercept=Math.max(0,fighter.fuel-sol.sec*.045), fuelAtBase=Math.max(0,fighter.fuel-fuelToBase*.045), endurance=fighter.fuel/.045/60
 const needRTB=fighter.airborne&&(fuelAtBase<RESERVE||fighter.fuel<=BINGO), needAAR=fighter.airborne&&fuelAtIntercept<RESERVE&&!needRTB
 const recommendation=needRTB?'RTB':needAAR&&tankerRange<=25?'AAR':'INTERCEPT'
 useEffect(()=>{if(!running)return;const id=setInterval(()=>{setT(a=>a.map(move));setF(a=>a.map(x=>x.airborne?move(x):x))},1000);return()=>clearInterval(id)},[running])
 const log=(s:string)=>setEvents(e=>[s,...e].slice(0,5))
 function scramble(){if(scrambled()){setMsg(`${fighter.name} already airborne.`);return};setF(a=>a.map(x=>x.id===selF?{...x,airborne:true}:x));const pts=Math.max(0,150-Math.round(baseRange*4));setScore(s=>s+pts);log(`QRA ${b.name}: +${pts}`);setMsg(`${b.name} QRA scrambled. Fuel ${Math.round(fighter.fuel)}%.`)}
 function scrambled(){return fighter.airborne}
 function vectorCmd(){if(!fighter.airborne){setMsg('FIGHTER NOT AIRBORNE — SCRAMBLE QRA FIRST.');return}if(fighter.fuel<=BINGO){setMsg('BINGO FUEL — VECTOR CANCELLED. ORDER RTB.');return}const e=ang(vector,sol.heading),pts=Math.max(0,140-Math.round(e*2));setScore(s=>s+pts);setF(a=>a.map(x=>x.id===selF?{...x,heading:vector}:x));log(`VECTOR ${String(vector).padStart(3,'0')}°: +${pts}`);setMsg(e<=8?`EXCELLENT VECTOR. +${pts}.`:`VECTOR ACCEPTED. +${pts}.`)}
 function rtb(){if(!fighter.airborne){setMsg('FIGHTER IS ON QRA AT BASE.');return}const h=brg(fighter,{...b,id:b.id,name:b.name,x:b.x,y:b.y,heading:0,speed:0,alt:0,fuel:0,airborne:false,friendly:true,trail:[]});setF(a=>a.map(x=>x.id===selF?{...x,heading:h}:x));const pts=fighter.fuel>RESERVE?80:30;setScore(s=>s+pts);log(`RTB ${b.name}: +${pts}`);setMsg(`RTB VECTOR ${String(h).padStart(3,'0')}°. ${pts} points.`)}
 function aar(){if(!fighter.airborne){setMsg('TANKER SUPPORT REQUIRES AIRBORNE FIGHTER.');return}if(tankerRange>25){setMsg(`VOYAGER ${tankerRange.toFixed(0)} NM — TOO FAR FOR AAR.`);return}const gain=Math.min(40,100-fighter.fuel);setF(a=>a.map(x=>x.id===selF?{...x,fuel:x.fuel+gain}:x));setScore(s=>s+gain*3);log(`AAR ${gain}%: +${gain*3}`);setMsg(`AAR COMPLETE. +${gain}% fuel.`)}
 function reset(){setT(initialT);setF(initialF);setScore(0);setEvents([]);setRunning(true);setMsg('NEW SCENARIO — CONTACT!')}
 return <main><header><div><div className="eyebrow">AIR DEFENCE TRAINING SYSTEM</div><h1>RAF INTERCEPT <span>STAGE 6</span></h1></div><div className="topright"><span>VERSION {VERSION}</span><b>NORTH SEA / UK AIR DEFENCE</b><i>● SIM</i></div></header>
 <section className="layout"><div className="radar"><div className="scope"><div className="rings r1"/><div className="rings r2"/><div className="rings r3"/><div className="cross v"/><div className="cross h"/><div className="sweep"/><div className="north">N</div><div className="west">W</div><div className="east">E</div><div className="south">S</div><div className="uk-outline"><span>UK</span></div><div className="europe-outline"><span>EUROPE</span></div>{bases.map(x=><button key={x.id} className={`base ${base===x.id?'chosen':''}`} style={{left:`${x.x}%`,top:`${x.y}%`}} onClick={()=>setBase(x.id)}>✦<small>{x.name}</small></button>)}<div className="tanker" style={{left:`${tanker.x}%`,top:`${tanker.y}%`}}>✚<small>VOYAGER</small></div>{t.map(x=><Contact key={x.id} p={x} sel={selT===x.id} onClick={()=>setSelT(x.id)}/>) }{f.map(x=><Contact key={x.id} p={x} sel={selF===x.id} onClick={()=>setSelF(x.id)}/>) }{assist&&<><div className="pip" style={{left:`${sol.x}%`,top:`${sol.y}%`}}>×</div><div className="solution-line" style={{left:`${fighter.x}%`,top:`${fighter.y}%`,width:`${Math.hypot(sol.x-fighter.x,sol.y-fighter.y)}%`,transform:`rotate(${sol.heading}deg)`}}/></>}<div className="scope-label">NORTH SEA AIR DEFENCE SECTOR</div><div className="scale">RANGE RINGS: 25 / 50 / 100 NM</div></div><div className="radar-footer"><span>SURVEILLANCE</span><span>CONTACTS {t.length+f.length}</span><span>1 SEC UPDATE</span></div></div>
 <aside><div className="panel"><h2>CONTACT ASSESSMENT</h2><div className="big">{target.name}</div><div className="grid"><label>BRG <strong>{String(bearing).padStart(3,'0')}°</strong></label><label>RNG <strong>{rng.toFixed(0)} NM</strong></label><label>SPD <strong>{target.speed} KT</strong></label><label>ALT <strong>FL{target.alt}</strong></label><label>HDG <strong>{String(target.heading).padStart(3,'0')}°</strong></label><label>THREAT <strong>UNKNOWN</strong></label></div></div>
 <div className="panel"><h2>FUEL / DECISION SUPPORT</h2><div className={`decision ${recommendation.toLowerCase()}`}><span>RECOMMENDED ACTION</span><b>{recommendation}</b></div><div className="grid"><label>FUEL <strong>{Math.round(fighter.fuel)}%</strong></label><label>ENDURANCE <strong>{endurance.toFixed(1)} MIN</strong></label><label>AT PIP <strong>{fuelAtIntercept.toFixed(0)}%</strong></label><label>AT BASE <strong>{fuelAtBase.toFixed(0)}%</strong></label><label>BASE RNG <strong>{baseRange.toFixed(0)} NM</strong></label><label>TANKER RNG <strong>{tankerRange.toFixed(0)} NM</strong></label></div><div className={`fuelbar ${fighter.fuel<=BINGO?'bingo':fighter.fuel<=RESERVE?'low':''}`}><span>BINGO {BINGO}%</span><b>{fighter.fuel<=BINGO?'BINGO':fighter.fuel<=RESERVE?'LOW':'GOOD'}</b></div></div>
 <div className="panel"><h2>QRA SELECTION</h2>{bases.map(x=><button className={`baseRow ${base===x.id?'active':''}`} key={x.id} onClick={()=>setBase(x.id)}><span>{x.name}</span><b>{x.aircraft} READY</b></button>)}<button className="primary" onClick={scramble}>SCRAMBLE SELECTED QRA</button></div>
 <div className="panel"><h2>VOYAGER AAR</h2><div className="grid"><label>HDG <strong>090°</strong></label><label>SPD <strong>410 KT</strong></label><label>RANGE <strong>{tankerRange.toFixed(0)} NM</strong></label><label>STATE <strong>AVAILABLE</strong></label></div><button className="primary" onClick={aar}>REQUEST AAR</button></div>
 <div className="panel command"><h2>VECTOR COMMAND</h2><input type="range" min="0" max="359" value={vector} onChange={e=>setVector(+e.target.value)}/><div className="vector"><span>VECTOR</span><strong>{String(vector).padStart(3,'0')}°</strong></div>{assist&&<div className="hint">TRAINING: {recommendation} · solution {String(sol.heading).padStart(3,'0')}°</div>}<div className="cmdrow"><button className="primary" onClick={vectorCmd}>ISSUE VECTOR</button><button className="secondary" onClick={rtb}>ORDER RTB</button></div></div>
 <div className="panel"><h2>CONTROLLER ASSESSMENT</h2><div className="score">{score}</div><p className="message">{msg}</p><label className="toggle"><input type="checkbox" checked={assist} onChange={e=>setAssist(e.target.checked)}/> Training assistance</label><div className="debrief">{events.map((x,i)=><div key={i}>{x}</div>)}</div><div className="actions"><button onClick={()=>setRunning(!running)}>{running?'PAUSE':'RESUME'}</button><button onClick={reset}>NEW SCENARIO</button></div></div></aside></section></main>
}